name: Deploy

on: [push]

jobs:
  deploy:
  	if: github.ref == 'refs/heads/master'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Push to server
      	uses: swimmer-zone/swimmer-react@master
      	with:
        	host: ${{ secrets.HOST }}
        	username: ${{ secrets.USERNAME }}
        	port: ${{ secrets.PORT }}
        	key: ${{ secrets.SSHKEY }}
        	script: cd ${{ secrets.REMOTE_PATH }} && git pull && npm install
