name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: actions/checkout@v1
      - run: |
          cd ~/actions-runner/_work/swimmer-react
          mv swimmer-react /var/www/swimmer-react
          cd /var/www/swimmer-react
          npm install
